/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01;

import com.google.common.base.Splitter;
import com.google.common.collect.Lists;
import java.util.ArrayList;
import java.util.Collections;

public class HelloOtus {
    public static void main(String... args) {
        String letter = "this words will be separated and shuffled";
        ArrayList<String> words = Lists.newArrayList(Splitter.on(' ').split(letter));
        Collections.shuffle(words);
        System.out.println(words);
    }
}
